import { Category, Deal } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-electronics', name: 'Electronics', slug: 'electronics', description: 'Smartphones, laptops, monitors and hardware' },
  { id: 'cat-audio', name: 'Audio & Sound', slug: 'audio', description: 'Headphones, earbuds, speakers and amplifiers' },
  { id: 'cat-gaming', name: 'Gaming', slug: 'gaming', description: 'Consoles, PC peripherals, games and accessories' },
  { id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen', description: 'Appliances, cookware, espresso machines and smart home' },
  { id: 'cat-fashion', name: 'Fashion & Apparel', slug: 'fashion', description: 'Sneakers, outerwear, minimalist essentials' },
  { id: 'cat-travel', name: 'Travel & Outdoors', slug: 'travel', description: 'Luggage, camping gear, backpacks and bags' },
];

// Helper to generate ISO dates relative to now
const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400 * 1000).toISOString();
const daysFromNow = (d: number) => new Date(now + d * 86400 * 1000).toISOString();

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal-1',
    title: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    short_description: 'Industry-leading noise cancellation with two processors and 8 microphones. 30-hour battery life with quick charge.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    original_price: 480000,
    discounted_price: 336000,
    percentage_off: 30,
    category_id: 'cat-audio',
    source_name: 'Amazon',
    source_url: 'https://www.amazon.com/dp/B09XS7JWHH',
    status: 'live',
    posted_at: hoursAgo(2),
    expires_at: daysFromNow(5),
  },
  {
    id: 'deal-2',
    title: 'Apple MacBook Air 15-inch M3 Chip (16GB RAM, 512GB SSD)',
    short_description: 'Stunning Liquid Retina display, thin fanless design, up to 18 hours battery life in sleek Midnight finish.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    original_price: 1950000,
    discounted_price: 1620000,
    percentage_off: 17,
    category_id: 'cat-electronics',
    source_name: 'Best Buy',
    source_url: 'https://www.bestbuy.com/site/apple-macbook-air-15-inch-m3/6534606.p',
    status: 'live',
    posted_at: hoursAgo(4),
    expires_at: daysFromNow(3),
  },
  {
    id: 'deal-3',
    title: 'Keychron Q1 Pro Custom Mechanical Keyboard (Wireless)',
    short_description: 'Full aluminum body, hot-swappable tactile banana switches, gasket mount design, and custom QMK/VIA key remapping.',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
    original_price: 240000,
    discounted_price: 180000,
    percentage_off: 25,
    category_id: 'cat-gaming',
    source_name: 'Keychron Store',
    source_url: 'https://www.keychron.com/products/keychron-q1-pro-qmk-via-wireless-custom-mechanical-keyboard',
    status: 'live',
    posted_at: hoursAgo(6),
    expires_at: daysFromNow(7),
  },
  {
    id: 'deal-4',
    title: 'Breville Barista Touch Impress Espresso Machine',
    short_description: 'Real-time feedback with assisted tamping, auto microfoam milk texturing, and thermoJet 3-second rapid heat-up system.',
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
    original_price: 1850000,
    discounted_price: 1480000,
    percentage_off: 20,
    category_id: 'cat-home',
    source_name: 'Williams Sonoma',
    source_url: 'https://www.williams-sonoma.com/products/breville-barista-touch-impress-espresso-machine',
    status: 'live',
    posted_at: hoursAgo(8),
    expires_at: daysFromNow(4),
  },
  {
    id: 'deal-5',
    title: 'Nike Pegasus 41 Road Running Shoes (Black/Volt)',
    short_description: 'Dual Air Zoom units with updated ReactX foam midsole providing 13% more energy return for daily distance training.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    original_price: 195000,
    discounted_price: 125000,
    percentage_off: 36,
    category_id: 'cat-fashion',
    source_name: 'Nike',
    source_url: 'https://www.nike.com/t/pegasus-41-mens-road-running-shoes-rn',
    status: 'live',
    posted_at: hoursAgo(11),
    expires_at: daysFromNow(6),
  },
  {
    id: 'deal-6',
    title: 'Peak Design Everyday Backpack V2 20L (Charcoal)',
    short_description: 'Weatherproof 400D recycled nylon canvas, dual MagLatch access, configurable FlexFold dividers for camera or everyday carry.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    original_price: 350000,
    discounted_price: 275000,
    percentage_off: 21,
    category_id: 'cat-travel',
    source_name: 'B&H Photo',
    source_url: 'https://www.bhphotovideo.com/c/product/1515286-REG/peak_design_bedb_20_ch_2_everyday_backpack_20l_v2.html',
    status: 'live',
    posted_at: hoursAgo(14),
    expires_at: daysFromNow(10),
  },
  {
    id: 'deal-7',
    title: 'LG UltraGear 27-inch OLED QHD 240Hz Gaming Monitor',
    short_description: '0.03ms response time, 98.5% DCI-P3 color gamut, NVIDIA G-SYNC compatible with anti-glare low-reflection coating.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    original_price: 1150000,
    discounted_price: 760000,
    percentage_off: 34,
    category_id: 'cat-gaming',
    source_name: 'B&H Photo',
    source_url: 'https://www.bhphotovideo.com/c/product/1744158-REG/lg_27gr95qe_b_27_ultragear_oled_qhd.html',
    status: 'live',
    posted_at: hoursAgo(18),
    expires_at: daysFromNow(2),
  },
  {
    id: 'deal-8',
    title: 'Sonos Move 2 Portable Smart Speaker with Wi-Fi & Bluetooth',
    short_description: 'Stereo acoustic architecture, 24-hour battery endurance, IP56 weather resistance, and automatic Trueplay room tuning.',
    image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
    original_price: 580000,
    discounted_price: 464000,
    percentage_off: 20,
    category_id: 'cat-audio',
    source_name: 'Sonos',
    source_url: 'https://www.sonos.com/en-us/shop/move-2',
    status: 'live',
    posted_at: hoursAgo(22),
    expires_at: daysFromNow(8),
  },
  {
    id: 'deal-9',
    title: 'Dyson V12 Detect Slim Absolute Cordless Vacuum',
    short_description: 'Laser illumination reveals invisible dust on hard floors. Piezo sensor automatically adjusts suction power.',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80',
    original_price: 850000,
    discounted_price: 585000,
    percentage_off: 31,
    category_id: 'cat-home',
    source_name: 'Target',
    source_url: 'https://www.target.com/p/dyson-v12-detect-slim-cordless-vacuum/-/A-86266453',
    status: 'live',
    posted_at: daysAgo(1),
    expires_at: daysFromNow(4),
  },
  {
    id: 'deal-10',
    title: 'Anker Prime 20,000mAh Power Bank (200W Output)',
    short_description: 'High-speed dual USB-C charging for two laptops simultaneously with built-in smart digital display and compact footprint.',
    image: 'https://images.unsplash.com/photo-1609592426806-039c9431f0cf?auto=format&fit=crop&w=800&q=80',
    original_price: 165000,
    discounted_price: 115000,
    percentage_off: 30,
    category_id: 'cat-electronics',
    source_name: 'Amazon',
    source_url: 'https://www.amazon.com/dp/B0BYP2F3SG',
    status: 'live',
    posted_at: daysAgo(1.2),
    expires_at: daysFromNow(9),
  },
  {
    id: 'deal-11',
    title: 'Patagonia Nano Puff Insulated Jacket (Black)',
    short_description: 'Warm, windproof, water-resistant PrimaLoft Gold Insulation Eco wrapped in 100% recycled polyester shell.',
    image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
    original_price: 310000,
    discounted_price: 217000,
    percentage_off: 30,
    category_id: 'cat-fashion',
    source_name: 'REI',
    source_url: 'https://www.rei.com/product/102390/patagonia-nano-puff-jacket-mens',
    status: 'live',
    posted_at: daysAgo(1.5),
    expires_at: daysFromNow(6),
  },
  {
    id: 'deal-12',
    title: 'Rimowa Classic Cabin Aluminum Carry-On Suitcase',
    short_description: 'Anodized aluminum alloy with high-end leather handles, TSA-approved combination locks, and smooth ball-bearing wheels.',
    image: 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=800&q=80',
    original_price: 1980000,
    discounted_price: 1680000,
    percentage_off: 15,
    category_id: 'cat-travel',
    source_name: 'Nordstrom',
    source_url: 'https://www.nordstrom.com/s/rimowa-classic-cabin-suitcase/5084920',
    status: 'live',
    posted_at: daysAgo(1.8),
    expires_at: daysFromNow(12),
  },
  {
    id: 'deal-13',
    title: 'Steam Deck OLED 512GB Handheld Gaming Console',
    short_description: '7.4-inch 90Hz HDR OLED screen, improved battery life, Wi-Fi 6E, and ergonomic grips for portable PC gaming.',
    image: 'https://images.unsplash.com/photo-1612287232230-011116c20524?auto=format&fit=crop&w=800&q=80',
    original_price: 720000,
    discounted_price: 640000,
    percentage_off: 11,
    category_id: 'cat-gaming',
    source_name: 'Valve Steam Store',
    source_url: 'https://store.steampowered.com/steamdeck',
    status: 'live',
    posted_at: daysAgo(2),
    expires_at: daysFromNow(5),
  },
  {
    id: 'deal-14',
    title: 'Kindle Paperwhite Signature Edition (32GB, Wireless Charging)',
    short_description: '6.8-inch glare-free display with adjustable warm light, auto-adjusting light sensor, and up to 10 weeks battery life.',
    image: 'https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=800&q=80',
    original_price: 245000,
    discounted_price: 180000,
    percentage_off: 27,
    category_id: 'cat-electronics',
    source_name: 'Amazon',
    source_url: 'https://www.amazon.com/dp/B08B495319',
    status: 'live',
    posted_at: daysAgo(2.3),
    expires_at: daysFromNow(3),
  },
  {
    id: 'deal-15',
    title: 'Fellow Stagg EKG Electric Gooseneck Pour-Over Kettle',
    short_description: 'Precision pour spout, variable temperature control, LCD display screen, and 60-minute brew hold mode.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
    original_price: 215000,
    discounted_price: 168000,
    percentage_off: 22,
    category_id: 'cat-home',
    source_name: 'Fellow Products',
    source_url: 'https://fellowproducts.com/products/stagg-ekg-electric-pour-over-kettle',
    status: 'live',
    posted_at: daysAgo(2.7),
    expires_at: daysFromNow(8),
  },
  {
    id: 'deal-16',
    title: 'Osprey Farpoint 40 Travel Pack (M/L, Black)',
    short_description: 'Meets airline carry-on regulations with stowable backpanel harness, padded laptop sleeve, and internal compression.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
    original_price: 240000,
    discounted_price: 180000,
    percentage_off: 25,
    category_id: 'cat-travel',
    source_name: 'REI',
    source_url: 'https://www.rei.com/product/207730/osprey-farpoint-40-travel-pack-mens',
    status: 'live',
    posted_at: daysAgo(3),
    expires_at: daysFromNow(11),
  },
  {
    id: 'deal-17',
    title: 'Shure SM7B Cardioid Dynamic Vocal Microphone',
    short_description: 'Legendary studio broadcast microphone with smooth, flat, wide-range frequency response and internal shock isolation.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    original_price: 520000,
    discounted_price: 416000,
    percentage_off: 20,
    category_id: 'cat-audio',
    source_name: 'Sweetwater',
    source_url: 'https://www.sweetwater.com/store/detail/SM7B--shure-sm7b-cardioid-dynamic-vocal-microphone',
    status: 'live',
    posted_at: daysAgo(3.5),
    expires_at: daysFromNow(4),
  },
  {
    id: 'deal-18',
    title: 'Levi’s Premium Vintage Fit Trucker Denim Jacket',
    short_description: 'Classic 100% heavyweight cotton denim with vintage silhouette, chest flap pockets, and side welt pockets.',
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    original_price: 165000,
    discounted_price: 99000,
    percentage_off: 40,
    category_id: 'cat-fashion',
    source_name: 'Levi.com',
    source_url: 'https://www.levi.com/US/en_US/clothing/men/outerwear/trucker-jackets/vintage-fit-trucker-jacket/p/773800015',
    status: 'live',
    posted_at: daysAgo(4),
    expires_at: daysFromNow(14),
  },
  {
    id: 'deal-19',
    title: 'Logitech MX Master 3S Wireless Performance Mouse',
    short_description: 'Quiet clicks, 8K DPI track-on-glass sensor, and MagSpeed electromagnetic scroll wheel for productivity setups.',
    image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
    original_price: 130000,
    discounted_price: 104000,
    percentage_off: 20,
    category_id: 'cat-electronics',
    source_name: 'Amazon',
    source_url: 'https://www.amazon.com/dp/B09HM94VDS',
    status: 'live',
    posted_at: daysAgo(4.5),
    expires_at: daysFromNow(5),
  },
  {
    id: 'deal-20',
    title: 'Le Creuset Enameled Cast Iron Signature Round Dutch Oven 5.5 Qt',
    short_description: 'Superior heat distribution and retention, durable enamel resists chipping and cracking. Dishwasher safe.',
    image: 'https://images.unsplash.com/photo-1584990347449-a2929e061803?auto=format&fit=crop&w=800&q=80',
    original_price: 550000,
    discounted_price: 380000,
    percentage_off: 31,
    category_id: 'cat-home',
    source_name: 'Sur La Table',
    source_url: 'https://www.surlatable.com/le-creuset-round-dutch-oven-55-qt/PRO-1025535.html',
    status: 'live',
    posted_at: daysAgo(5),
    expires_at: daysFromNow(15),
  },
  // Expired sample deal (MUST be excluded from public feed)
  {
    id: 'deal-expired-flash',
    title: 'Samsung 65" Class OLED S90D 4K TV [Flash Deal - Expired]',
    short_description: 'OLED with Neural Quantum Processor 4K, 144Hz refresh rate, Dolby Atmos. Limited 24h flash clearance.',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
    original_price: 2600000,
    discounted_price: 1820000,
    percentage_off: 30,
    category_id: 'cat-electronics',
    source_name: 'Samsung Store',
    source_url: 'https://www.samsung.com/us/televisions-home-theater/tvs/oled-tvs/',
    status: 'expired',
    posted_at: daysAgo(8),
    expires_at: daysAgo(1), // Past expiration date
  },
  // Draft sample deal (MUST be excluded from public feed)
  {
    id: 'deal-draft-preview',
    title: 'Bose QuietComfort Ultra Earbuds [Admin Draft]',
    short_description: 'World-class noise cancellation, breakthrough spatialized audio, custom tune technology. Pending launch.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    original_price: 390000,
    discounted_price: 325000,
    percentage_off: 17,
    category_id: 'cat-audio',
    source_name: 'Bose',
    source_url: 'https://www.bose.com/p/earbuds/bose-quietcomfort-ultra-earbuds/QCULT-HEADPHONEIN.html',
    status: 'draft',
    posted_at: daysAgo(1),
    expires_at: daysFromNow(20),
  },
];
