from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import timedelta
from decimal import Decimal
from deals.models import Category, Deal

class Command(BaseCommand):
    help = 'Seeds database with categories and ~20 realistic deals for testing feed discovery'

    def handle(self, *args, **options):
        self.stdout.write('Seeding DealPulse categories and deals...')

        categories_data = [
            {'name': 'Electronics', 'slug': 'electronics', 'description': 'Smartphones, laptops, monitors and hardware'},
            {'name': 'Audio & Sound', 'slug': 'audio', 'description': 'Headphones, earbuds, speakers and amplifiers'},
            {'name': 'Gaming', 'slug': 'gaming', 'description': 'Consoles, PC peripherals, games and accessories'},
            {'name': 'Home & Kitchen', 'slug': 'home-kitchen', 'description': 'Appliances, cookware, espresso machines and smart home'},
            {'name': 'Fashion & Apparel', 'slug': 'fashion', 'description': 'Sneakers, outerwear, minimalist essentials'},
            {'name': 'Travel & Outdoors', 'slug': 'travel', 'description': 'Luggage, camping gear, backpacks and bags'},
        ]

        cat_map = {}
        for c in categories_data:
            cat, _ = Category.objects.update_or_create(
                slug=c['slug'],
                defaults={'name': c['name'], 'description': c['description']}
            )
            cat_map[c['slug']] = cat

        now = timezone.now()

        sample_deals = [
            {
                'title': 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
                'short_description': 'Industry-leading noise cancellation with two processors and 8 microphones. 30-hour battery life with quick charge.',
                'image_url': 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('480000.00'),
                'discounted_price': Decimal('336000.00'),
                'percentage_off': 30,
                'category': cat_map['audio'],
                'source_name': 'Amazon',
                'source_url': 'https://www.amazon.com/dp/B09XS7JWHH',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=2),
                'expires_at': now + timedelta(days=5),
            },
            {
                'title': 'Apple MacBook Air 15-inch M3 Chip (16GB RAM, 512GB SSD)',
                'short_description': 'Stunning Liquid Retina display, thin fanless design, up to 18 hours battery life in sleek Midnight finish.',
                'image_url': 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('1950000.00'),
                'discounted_price': Decimal('1620000.00'),
                'percentage_off': 17,
                'category': cat_map['electronics'],
                'source_name': 'Best Buy',
                'source_url': 'https://www.bestbuy.com/site/apple-macbook-air-15-inch-m3/6534606.p',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=4),
                'expires_at': now + timedelta(days=3),
            },
            {
                'title': 'Keychron Q1 Pro Custom Mechanical Keyboard (Wireless)',
                'short_description': 'Full aluminum body, hot-swappable tactile banana switches, gasket mount design, and custom QMK/VIA key remapping.',
                'image_url': 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('240000.00'),
                'discounted_price': Decimal('180000.00'),
                'percentage_off': 25,
                'category': cat_map['gaming'],
                'source_name': 'Keychron Store',
                'source_url': 'https://www.keychron.com/products/keychron-q1-pro-qmk-via-wireless-custom-mechanical-keyboard',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=6),
                'expires_at': now + timedelta(days=7),
            },
            {
                'title': 'Breville Barista Touch Impress Espresso Machine',
                'short_description': 'Real-time feedback with assisted tamping, auto microfoam milk texturing, and thermoJet 3-second rapid heat-up system.',
                'image_url': 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('1850000.00'),
                'discounted_price': Decimal('1480000.00'),
                'percentage_off': 20,
                'category': cat_map['home-kitchen'],
                'source_name': 'Williams Sonoma',
                'source_url': 'https://www.williams-sonoma.com/products/breville-barista-touch-impress-espresso-machine',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=8),
                'expires_at': now + timedelta(days=4),
            },
            {
                'title': 'Nike Pegasus 41 Road Running Shoes (Black/Volt)',
                'short_description': 'Dual Air Zoom units with updated ReactX foam midsole providing 13% more energy return for daily distance training.',
                'image_url': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('195000.00'),
                'discounted_price': Decimal('125000.00'),
                'percentage_off': 36,
                'category': cat_map['fashion'],
                'source_name': 'Nike',
                'source_url': 'https://www.nike.com/t/pegasus-41-mens-road-running-shoes-rn',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=11),
                'expires_at': now + timedelta(days=6),
            },
            {
                'title': 'Peak Design Everyday Backpack V2 20L (Charcoal)',
                'short_description': 'Weatherproof 400D recycled nylon canvas, dual MagLatch access, configurable FlexFold dividers for camera or everyday carry.',
                'image_url': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('350000.00'),
                'discounted_price': Decimal('275000.00'),
                'percentage_off': 21,
                'category': cat_map['travel'],
                'source_name': 'B&H Photo',
                'source_url': 'https://www.bhphotovideo.com/c/product/1515286-REG/peak_design_bedb_20_ch_2_everyday_backpack_20l_v2.html',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=14),
                'expires_at': now + timedelta(days=10),
            },
            {
                'title': 'LG UltraGear 27-inch OLED QHD 240Hz Gaming Monitor',
                'short_description': '0.03ms response time, 98.5% DCI-P3 color gamut, NVIDIA G-SYNC compatible with anti-glare low-reflection coating.',
                'image_url': 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('1150000.00'),
                'discounted_price': Decimal('760000.00'),
                'percentage_off': 34,
                'category': cat_map['gaming'],
                'source_name': 'B&H Photo',
                'source_url': 'https://www.bhphotovideo.com/c/product/1744158-REG/lg_27gr95qe_b_27_ultragear_oled_qhd.html',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=18),
                'expires_at': now + timedelta(days=2),
            },
            {
                'title': 'Sonos Move 2 Portable Smart Speaker with Wi-Fi & Bluetooth',
                'short_description': 'Stereo acoustic architecture, 24-hour battery endurance, IP56 weather resistance, and automatic Trueplay room tuning.',
                'image_url': 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('580000.00'),
                'discounted_price': Decimal('464000.00'),
                'percentage_off': 20,
                'category': cat_map['audio'],
                'source_name': 'Sonos',
                'source_url': 'https://www.sonos.com/en-us/shop/move-2',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(hours=22),
                'expires_at': now + timedelta(days=8),
            },
            {
                'title': 'Dyson V12 Detect Slim Absolute Cordless Vacuum',
                'short_description': 'Laser illumination reveals invisible dust on hard floors. Piezo sensor automatically adjusts suction power.',
                'image_url': 'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('850000.00'),
                'discounted_price': Decimal('585000.00'),
                'percentage_off': 31,
                'category': cat_map['home-kitchen'],
                'source_name': 'Target',
                'source_url': 'https://www.target.com/p/dyson-v12-detect-slim-cordless-vacuum/-/A-86266453',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=1),
                'expires_at': now + timedelta(days=4),
            },
            {
                'title': 'Anker Prime 20,000mAh Power Bank (200W Output)',
                'short_description': 'High-speed dual USB-C charging for two laptops simultaneously with built-in smart digital display and compact footprint.',
                'image_url': 'https://images.unsplash.com/photo-1609592426806-039c9431f0cf?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('165000.00'),
                'discounted_price': Decimal('115000.00'),
                'percentage_off': 30,
                'category': cat_map['electronics'],
                'source_name': 'Amazon',
                'source_url': 'https://www.amazon.com/dp/B0BYP2F3SG',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=1, hours=4),
                'expires_at': now + timedelta(days=9),
            },
            {
                'title': 'Patagonia Nano Puff Insulated Jacket (Black)',
                'short_description': 'Warm, windproof, water-resistant PrimaLoft Gold Insulation Eco wrapped in 100% recycled polyester shell.',
                'image_url': 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('310000.00'),
                'discounted_price': Decimal('217000.00'),
                'percentage_off': 30,
                'category': cat_map['fashion'],
                'source_name': 'REI',
                'source_url': 'https://www.rei.com/product/102390/patagonia-nano-puff-jacket-mens',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=1, hours=10),
                'expires_at': now + timedelta(days=6),
            },
            {
                'title': 'Rimowa Classic Cabin Aluminum Carry-On Suitcase',
                'short_description': 'Anodized aluminum alloy with high-end leather handles, TSA-approved combination locks, and smooth ball-bearing wheels.',
                'image_url': 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('1980000.00'),
                'discounted_price': Decimal('1680000.00'),
                'percentage_off': 15,
                'category': cat_map['travel'],
                'source_name': 'Nordstrom',
                'source_url': 'https://www.nordstrom.com/s/rimowa-classic-cabin-suitcase/5084920',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=1, hours=18),
                'expires_at': now + timedelta(days=12),
            },
            {
                'title': 'Steam Deck OLED 512GB Handheld Gaming Console',
                'short_description': '7.4-inch 90Hz HDR OLED screen, improved battery life, Wi-Fi 6E, and ergonomic grips for portable PC gaming.',
                'image_url': 'https://images.unsplash.com/photo-1612287232230-011116c20524?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('720000.00'),
                'discounted_price': Decimal('640000.00'),
                'percentage_off': 11,
                'category': cat_map['gaming'],
                'source_name': 'Valve Steam Store',
                'source_url': 'https://store.steampowered.com/steamdeck',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=2),
                'expires_at': now + timedelta(days=5),
            },
            {
                'title': 'Kindle Paperwhite Signature Edition (32GB, Wireless Charging)',
                'short_description': '6.8-inch glare-free display with adjustable warm light, auto-adjusting light sensor, and up to 10 weeks battery life.',
                'image_url': 'https://images.unsplash.com/photo-1592496001020-d31bd830651f?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('245000.00'),
                'discounted_price': Decimal('180000.00'),
                'percentage_off': 27,
                'category': cat_map['electronics'],
                'source_name': 'Amazon',
                'source_url': 'https://www.amazon.com/dp/B08B495319',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=2, hours=6),
                'expires_at': now + timedelta(days=3),
            },
            {
                'title': 'Fellow Stagg EKG Electric Gooseneck Pour-Over Kettle',
                'short_description': 'Precision pour spout, variable temperature control, LCD display screen, and 60-minute brew hold mode.',
                'image_url': 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('215000.00'),
                'discounted_price': Decimal('168000.00'),
                'percentage_off': 22,
                'category': cat_map['home-kitchen'],
                'source_name': 'Fellow Products',
                'source_url': 'https://fellowproducts.com/products/stagg-ekg-electric-pour-over-kettle',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=2, hours=14),
                'expires_at': now + timedelta(days=8),
            },
            {
                'title': 'Osprey Farpoint 40 Travel Pack (M/L, Black)',
                'short_description': 'Meets airline carry-on regulations with stowable backpanel harness, padded laptop sleeve, and internal compression.',
                'image_url': 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('240000.00'),
                'discounted_price': Decimal('180000.00'),
                'percentage_off': 25,
                'category': cat_map['travel'],
                'source_name': 'REI',
                'source_url': 'https://www.rei.com/product/207730/osprey-farpoint-40-travel-pack-mens',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=3),
                'expires_at': now + timedelta(days=11),
            },
            {
                'title': 'Shure SM7B Cardioid Dynamic Vocal Microphone',
                'short_description': 'Legendary studio broadcast microphone with smooth, flat, wide-range frequency response and internal shock isolation.',
                'image_url': 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('520000.00'),
                'discounted_price': Decimal('416000.00'),
                'percentage_off': 20,
                'category': cat_map['audio'],
                'source_name': 'Sweetwater',
                'source_url': 'https://www.sweetwater.com/store/detail/SM7B--shure-sm7b-cardioid-dynamic-vocal-microphone',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=3, hours=8),
                'expires_at': now + timedelta(days=4),
            },
            {
                'title': 'Levi’s Premium Vintage Fit Trucker Denim Jacket',
                'short_description': 'Classic 100% heavyweight cotton denim with vintage silhouette, chest flap pockets, and side welt pockets.',
                'image_url': 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('165000.00'),
                'discounted_price': Decimal('99000.00'),
                'percentage_off': 40,
                'category': cat_map['fashion'],
                'source_name': 'Levi.com',
                'source_url': 'https://www.levi.com/US/en_US/clothing/men/outerwear/trucker-jackets/vintage-fit-trucker-jacket/p/773800015',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=4),
                'expires_at': now + timedelta(days=14),
            },
            {
                'title': 'Logitech MX Master 3S Wireless Performance Mouse',
                'short_description': 'Quiet clicks, 8K DPI track-on-glass sensor, and MagSpeed electromagnetic scroll wheel for productivity setups.',
                'image_url': 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('130000.00'),
                'discounted_price': Decimal('104000.00'),
                'percentage_off': 20,
                'category': cat_map['electronics'],
                'source_name': 'Amazon',
                'source_url': 'https://www.amazon.com/dp/B09HM94VDS',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=4, hours=10),
                'expires_at': now + timedelta(days=5),
            },
            {
                'title': 'Le Creuset Enameled Cast Iron Round Dutch Oven 5.5 Qt',
                'short_description': 'Superior heat distribution and retention, durable enamel resists chipping and cracking. Dishwasher safe.',
                'image_url': 'https://images.unsplash.com/photo-1584990347449-a2929e061803?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('550000.00'),
                'discounted_price': Decimal('380000.00'),
                'percentage_off': 31,
                'category': cat_map['home-kitchen'],
                'source_name': 'Sur La Table',
                'source_url': 'https://www.surlatable.com/le-creuset-round-dutch-oven-55-qt/PRO-1025535.html',
                'status': Deal.Status.LIVE,
                'posted_at': now - timedelta(days=5),
                'expires_at': now + timedelta(days=15),
            },
            # Explicitly expired deal (for testing exclusion)
            {
                'title': 'Samsung 65" Class OLED S90D 4K TV [Flash Deal - Expired]',
                'short_description': 'OLED with Neural Quantum Processor 4K, 144Hz refresh rate, Dolby Atmos. Limited 24h flash clearance.',
                'image_url': 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('2600000.00'),
                'discounted_price': Decimal('1820000.00'),
                'percentage_off': 30,
                'category': cat_map['electronics'],
                'source_name': 'Samsung Store',
                'source_url': 'https://www.samsung.com/us/televisions-home-theater/tvs/oled-tvs/',
                'status': Deal.Status.EXPIRED,
                'posted_at': now - timedelta(days=8),
                'expires_at': now - timedelta(days=1),
            },
            # Explicitly draft deal (for testing exclusion)
            {
                'title': 'Bose QuietComfort Ultra Earbuds [Admin Draft]',
                'short_description': 'World-class noise cancellation, breakthrough spatialized audio, custom tune technology. Pending launch.',
                'image_url': 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
                'original_price': Decimal('390000.00'),
                'discounted_price': Decimal('325000.00'),
                'percentage_off': 17,
                'category': cat_map['audio'],
                'source_name': 'Bose',
                'source_url': 'https://www.bose.com/p/earbuds/bose-quietcomfort-ultra-earbuds/QCULT-HEADPHONEIN.html',
                'status': Deal.Status.DRAFT,
                'posted_at': now - timedelta(days=1),
                'expires_at': now + timedelta(days=20),
            },
        ]

        count = 0
        for item in sample_deals:
            Deal.objects.update_or_create(
                title=item['title'],
                defaults=item
            )
            count += 1

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(categories_data)} categories and {count} deals!'))
